FROM ubuntu:22.04

RUN apt-get update && apt-get install -y fonts-unfonts-core fonts-unfonts-extra wget unzip python3-pip
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN wget https://dl-ssl.google.com/linux/linux_signing_key.pub -O /tmp/google.pub
RUN wget https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
RUN gpg --no-default-keyring --keyring /etc/apt/keyrings/google-chrome.gpg --import /tmp/google.pub
RUN echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update && apt-get install -y google-chrome-stable
RUN unzip ./chromedriver_linux64.zip
#python setting
COPY ./source.py source.py
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN playwright install
ENTRYPOINT ["python3", "/source.py"]
